package uk.co.ultravisual.fontrenderer.utils;

class FontNames{

    public static var names:Dynamic = {
            glyphs:[
                  {
                     key:"space",
                     value:" "
                  },
                  {
                     key:"exclam",
                     value:"!"
                  },
                  {
                     key:"quotedbl",
                     value:"\""
                  },
                  {
                     key:"numbersign",
                     value:"#"
                  },
                  {
                     key:"dollar",
                     value:"$"
                  },
                  {
                     key:"percent",
                     value:"%"
                  },
                  {
                     key:"ampersand",
                     value:"&"
                  },
                  {
                     key:"quotesingle",
                     value:"'"
                  },
                  {
                     key:"parenleft",
                     value:"("
                  },
                  {
                     key:"parenright",
                     value:")"
                  },
                  {
                     key:"asterisk",
                     value:"*"
                  },
                  {
                     key:"plus",
                     value:"+"
                  },
                  {
                     key:"comma",
                     value:","
                  },
                  {
                     key:"hyphen",
                     value:"-"
                  },
                  {
                     key:"period",
                     value:"."
                  },
                  {
                     key:"slash",
                     value:"/"
                  },
                  {
                     key:"zero",
                     value:"0"
                  },
                  {
                     key:"one",
                     value:"1"
                  },
                  {
                     key:"two",
                     value:"2"
                  },
                  {
                     key:"three",
                     value:"3"
                  },
                  {
                     key:"four",
                     value:"4"
                  },
                  {
                     key:"five",
                     value:"5"
                  },
                  {
                     key:"six",
                     value:"6"
                  },
                  {
                     key:"seven",
                     value:"7"
                  },
                  {
                     key:"eight",
                     value:"8"
                  },
                  {
                     key:"nine",
                     value:"9"
                  },
                  {
                     key:"zero",
                     value:"0"
                  },
                  {
                     key:"colon",
                     value:":"
                  },
                  {
                     key:"semicolon",
                     value:";"
                  },
                  {
                     key:"less",
                     value:"<"
                  },
                  {
                     key:"equal",
                     value:"="
                  },
                  {
                     key:"greater",
                     value:">"
                  },
                  {
                     key:"question",
                     value:"?"
                  },
                  {
                     key:"at",
                     value:"@"
                  },
                  {
                     key:"A",
                     value:"A"
                  },
                  {
                     key:"B",
                     value:"B"
                  },
                  {
                     key:"C",
                     value:"C"
                  },
                  {
                     key:"D",
                     value:"D"
                  },
                  {
                     key:"E",
                     value:"E"
                  },
                  {
                     key:"F",
                     value:"F"
                  },
                  {
                     key:"G",
                     value:"G"
                  },
                  {
                     key:"H",
                     value:"H"
                  },
                  {
                     key:"I",
                     value:"I"
                  },
                  {
                     key:"J",
                     value:"J"
                  },
                  {
                     key:"K",
                     value:"K"
                  },
                  {
                     key:"L",
                     value:"L"
                  },
                  {
                     key:"M",
                     value:"M"
                  },
                  {
                     key:"N",
                     value:"N"
                  },
                  {
                     key:"O",
                     value:"O"
                  },
                  {
                     key:"P",
                     value:"P"
                  },
                  {
                     key:"Q",
                     value:"Q"
                  },
                  {
                     key:"R",
                     value:"R"
                  },
                  {
                     key:"S",
                     value:"S"
                  },
                  {
                     key:"T",
                     value:"T"
                  },
                  {
                     key:"U",
                     value:"U"
                  },
                  {
                     key:"V",
                     value:"V"
                  },
                  {
                     key:"W",
                     value:"W"
                  },
                  {
                     key:"X",
                     value:"X"
                  },
                  {
                     key:"Y",
                     value:"Y"
                  },
                  {
                     key:"Z",
                     value:"Z"
                  },
                  {
                     key:"bracketleft",
                     value:"["
                  },
                  {
                     key:"backslash",
                     value:"\""
                  },
                  {
                     key:"bracketright",
                     value:"]"
                  },
                  {
                     key:"underscore",
                     value:"_"
                  },
                  {
                     key:"a",
                     value:"a"
                  },
                  {
                     key:"b",
                     value:"b"
                  },
                  {
                     key:"c",
                     value:"c"
                  },
                  {
                     key:"d",
                     value:"d"
                  },
                  {
                     key:"e",
                     value:"e"
                  },
                  {
                     key:"f",
                     value:"f"
                  },
                  {
                     key:"g",
                     value:"g"
                  },
                  {
                     key:"h",
                     value:"h"
                  },
                  {
                     key:"i",
                     value:"i"
                  },
                  {
                     key:"j",
                     value:"j"
                  },
                  {
                     key:"k",
                     value:"k"
                  },
                  {
                     key:"l",
                     value:"l"
                  },
                  {
                     key:"m",
                     value:"m"
                  },
                  {
                     key:"n",
                     value:"n"
                  },
                  {
                     key:"o",
                     value:"o"
                  },
                  {
                     key:"p",
                     value:"p"
                  },
                  {
                     key:"q",
                     value:"q"
                  },
                  {
                     key:"r",
                     value:"r"
                  },
                  {
                     key:"s",
                     value:"s"
                  },
                  {
                     key:"t",
                     value:"t"
                  },
                  {
                     key:"u",
                     value:"u"
                  },
                  {
                     key:"v",
                     value:"v"
                  },
                  {
                     key:"w",
                     value:"w"
                  },
                  {
                     key:"x",
                     value:"x"
                  },
                  {
                     key:"y",
                     value:"y"
                  },
                  {
                     key:"z",
                     value:"z"
                  },
                  {
                     key:"braceleft",
                     value:"{"
                  },
                  {
                     key:"bar",
                     value:"|"
                  },
                  {
                     key:"braceright",
                     value:"}"
                  },
                  {
                     key:"asciitilde",
                     value:"~"
                  },
                  {
                     key:"cent",
                     value:"c"
                  },
                  {
                     key:"sterling",
                     value:"£"
                  }
               ]
            };

    public static function getValueFromName(name:String):String {
        var asArray:Array<GlyphInfo> = getAsArray();
        for (i in 0...asArray.length) {
            if (asArray[i].getKey() == name) {
                return asArray[i].getValue();
            }
        }
        return ".notdef";
    }

    public static function getAsArray():Array<GlyphInfo> {
        var glyphList:Array<GlyphInfo> = new Array<GlyphInfo>();
        var glyphObjs:Array<Dynamic> = names.glyphs;
        for (i in 0...glyphObjs.length) {
            glyphList.push(new GlyphInfo(glyphObjs[i].key, glyphObjs[i].value));
        }
        return glyphList;
    }
}